// @generated by `cargo run -p icc-gen --bin cicp_bundle_gen` — do not edit by hand.
//
// Index for the transfer-grouped, LZ4-HC compressed CICP ICC bundle
// (`../profiles/cicp_bundle.lz4`). Regenerate with the generator above
// after a moxcms version bump; the golden sha256 test will flag drift.

/// One LZ4-HC compressed group inside the bundle blob, keyed by
/// transfer-characteristics code. Each group's decoded bytes pack every
/// unique profile that shares that transfer.
#[derive(Clone, Copy)]
pub(crate) struct BundleGroup {
    /// H.273 transfer-characteristics code this group covers.
    pub transfer: u8,
    /// Byte offset of the group's LZ4 block within `CICP_BUNDLE_LZ4`.
    pub blob_offset: usize,
    /// Length of the group's LZ4 block.
    pub compressed_len: usize,
    /// Exact size of the group's decoded bytes (the `decompress_into` buffer).
    pub decompressed_len: usize,
}

/// Locator for one synthesized profile: which group holds it, and the
/// `[offset, offset + len)` slice of that group's *decoded* bytes.
#[derive(Clone, Copy)]
pub(crate) struct BundleProfile {
    /// H.273 colour-primaries code.
    pub primaries: u8,
    /// H.273 transfer-characteristics code.
    pub transfer: u8,
    /// Index into [`BUNDLE_GROUPS`].
    pub group_index: usize,
    /// Byte offset of this profile within the group's decoded bytes.
    pub offset_in_group: usize,
    /// Length of this profile in bytes.
    pub len: usize,
}

/// The concatenated LZ4-HC compressed groups. Embedded at compile time.
pub(crate) static CICP_BUNDLE_LZ4: &[u8] = include_bytes!("../profiles/cicp_bundle.lz4");

/// Number of transfer groups in the bundle.
pub(crate) const NUM_GROUPS: usize = 16;

/// Group table, indexed by group index (also the order in the blob).
pub(crate) static BUNDLE_GROUPS: [BundleGroup; NUM_GROUPS] = [
    BundleGroup { transfer: 1, blob_offset: 0, compressed_len: 603, decompressed_len: 4400 }, // 10 profile(s)
    BundleGroup { transfer: 4, blob_offset: 603, compressed_len: 626, decompressed_len: 4246 }, // 11 profile(s)
    BundleGroup { transfer: 5, blob_offset: 1229, compressed_len: 626, decompressed_len: 4246 }, // 11 profile(s)
    BundleGroup { transfer: 6, blob_offset: 1855, compressed_len: 646, decompressed_len: 4840 }, // 11 profile(s)
    BundleGroup { transfer: 7, blob_offset: 2501, compressed_len: 2937, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 8, blob_offset: 5438, compressed_len: 626, decompressed_len: 4246 }, // 11 profile(s)
    BundleGroup { transfer: 9, blob_offset: 6064, compressed_len: 2938, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 10, blob_offset: 9002, compressed_len: 2938, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 11, blob_offset: 11940, compressed_len: 2937, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 12, blob_offset: 14877, compressed_len: 2935, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 13, blob_offset: 17812, compressed_len: 604, decompressed_len: 4400 }, // 10 profile(s)
    BundleGroup { transfer: 14, blob_offset: 18416, compressed_len: 646, decompressed_len: 4840 }, // 11 profile(s)
    BundleGroup { transfer: 15, blob_offset: 19062, compressed_len: 646, decompressed_len: 4840 }, // 11 profile(s)
    BundleGroup { transfer: 16, blob_offset: 19708, compressed_len: 2564, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 17, blob_offset: 22272, compressed_len: 2843, decompressed_len: 71764 }, // 11 profile(s)
    BundleGroup { transfer: 18, blob_offset: 25115, compressed_len: 2886, decompressed_len: 71764 }, // 11 profile(s)
];

/// Profile locator table, sorted by `(primaries, transfer)` for binary search.
pub(crate) static BUNDLE_PROFILES: [BundleProfile; 174] = [
    BundleProfile { primaries: 1, transfer: 4, group_index: 1, offset_in_group: 0, len: 386 },
    BundleProfile { primaries: 1, transfer: 5, group_index: 2, offset_in_group: 0, len: 386 },
    BundleProfile { primaries: 1, transfer: 6, group_index: 3, offset_in_group: 0, len: 440 },
    BundleProfile { primaries: 1, transfer: 7, group_index: 4, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 8, group_index: 5, offset_in_group: 0, len: 386 },
    BundleProfile { primaries: 1, transfer: 9, group_index: 6, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 10, group_index: 7, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 11, group_index: 8, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 12, group_index: 9, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 14, group_index: 11, offset_in_group: 0, len: 440 },
    BundleProfile { primaries: 1, transfer: 15, group_index: 12, offset_in_group: 0, len: 440 },
    BundleProfile { primaries: 1, transfer: 16, group_index: 13, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 17, group_index: 14, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 1, transfer: 18, group_index: 15, offset_in_group: 0, len: 6524 },
    BundleProfile { primaries: 4, transfer: 1, group_index: 0, offset_in_group: 0, len: 440 },
    BundleProfile { primaries: 4, transfer: 4, group_index: 1, offset_in_group: 386, len: 386 },
    BundleProfile { primaries: 4, transfer: 5, group_index: 2, offset_in_group: 386, len: 386 },
    BundleProfile { primaries: 4, transfer: 6, group_index: 3, offset_in_group: 440, len: 440 },
    BundleProfile { primaries: 4, transfer: 7, group_index: 4, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 8, group_index: 5, offset_in_group: 386, len: 386 },
    BundleProfile { primaries: 4, transfer: 9, group_index: 6, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 10, group_index: 7, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 11, group_index: 8, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 12, group_index: 9, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 13, group_index: 10, offset_in_group: 0, len: 440 },
    BundleProfile { primaries: 4, transfer: 14, group_index: 11, offset_in_group: 440, len: 440 },
    BundleProfile { primaries: 4, transfer: 15, group_index: 12, offset_in_group: 440, len: 440 },
    BundleProfile { primaries: 4, transfer: 16, group_index: 13, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 17, group_index: 14, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 4, transfer: 18, group_index: 15, offset_in_group: 6524, len: 6524 },
    BundleProfile { primaries: 5, transfer: 1, group_index: 0, offset_in_group: 440, len: 440 },
    BundleProfile { primaries: 5, transfer: 4, group_index: 1, offset_in_group: 772, len: 386 },
    BundleProfile { primaries: 5, transfer: 5, group_index: 2, offset_in_group: 772, len: 386 },
    BundleProfile { primaries: 5, transfer: 6, group_index: 3, offset_in_group: 880, len: 440 },
    BundleProfile { primaries: 5, transfer: 7, group_index: 4, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 8, group_index: 5, offset_in_group: 772, len: 386 },
    BundleProfile { primaries: 5, transfer: 9, group_index: 6, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 10, group_index: 7, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 11, group_index: 8, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 12, group_index: 9, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 13, group_index: 10, offset_in_group: 440, len: 440 },
    BundleProfile { primaries: 5, transfer: 14, group_index: 11, offset_in_group: 880, len: 440 },
    BundleProfile { primaries: 5, transfer: 15, group_index: 12, offset_in_group: 880, len: 440 },
    BundleProfile { primaries: 5, transfer: 16, group_index: 13, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 17, group_index: 14, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 5, transfer: 18, group_index: 15, offset_in_group: 13048, len: 6524 },
    BundleProfile { primaries: 6, transfer: 1, group_index: 0, offset_in_group: 880, len: 440 },
    BundleProfile { primaries: 6, transfer: 4, group_index: 1, offset_in_group: 1158, len: 386 },
    BundleProfile { primaries: 6, transfer: 5, group_index: 2, offset_in_group: 1158, len: 386 },
    BundleProfile { primaries: 6, transfer: 6, group_index: 3, offset_in_group: 1320, len: 440 },
    BundleProfile { primaries: 6, transfer: 7, group_index: 4, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 8, group_index: 5, offset_in_group: 1158, len: 386 },
    BundleProfile { primaries: 6, transfer: 9, group_index: 6, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 10, group_index: 7, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 11, group_index: 8, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 12, group_index: 9, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 13, group_index: 10, offset_in_group: 880, len: 440 },
    BundleProfile { primaries: 6, transfer: 14, group_index: 11, offset_in_group: 1320, len: 440 },
    BundleProfile { primaries: 6, transfer: 15, group_index: 12, offset_in_group: 1320, len: 440 },
    BundleProfile { primaries: 6, transfer: 16, group_index: 13, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 17, group_index: 14, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 6, transfer: 18, group_index: 15, offset_in_group: 19572, len: 6524 },
    BundleProfile { primaries: 7, transfer: 1, group_index: 0, offset_in_group: 1320, len: 440 },
    BundleProfile { primaries: 7, transfer: 4, group_index: 1, offset_in_group: 1544, len: 386 },
    BundleProfile { primaries: 7, transfer: 5, group_index: 2, offset_in_group: 1544, len: 386 },
    BundleProfile { primaries: 7, transfer: 6, group_index: 3, offset_in_group: 1760, len: 440 },
    BundleProfile { primaries: 7, transfer: 7, group_index: 4, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 8, group_index: 5, offset_in_group: 1544, len: 386 },
    BundleProfile { primaries: 7, transfer: 9, group_index: 6, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 10, group_index: 7, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 11, group_index: 8, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 12, group_index: 9, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 13, group_index: 10, offset_in_group: 1320, len: 440 },
    BundleProfile { primaries: 7, transfer: 14, group_index: 11, offset_in_group: 1760, len: 440 },
    BundleProfile { primaries: 7, transfer: 15, group_index: 12, offset_in_group: 1760, len: 440 },
    BundleProfile { primaries: 7, transfer: 16, group_index: 13, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 17, group_index: 14, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 7, transfer: 18, group_index: 15, offset_in_group: 26096, len: 6524 },
    BundleProfile { primaries: 8, transfer: 1, group_index: 0, offset_in_group: 1760, len: 440 },
    BundleProfile { primaries: 8, transfer: 4, group_index: 1, offset_in_group: 1930, len: 386 },
    BundleProfile { primaries: 8, transfer: 5, group_index: 2, offset_in_group: 1930, len: 386 },
    BundleProfile { primaries: 8, transfer: 6, group_index: 3, offset_in_group: 2200, len: 440 },
    BundleProfile { primaries: 8, transfer: 7, group_index: 4, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 8, group_index: 5, offset_in_group: 1930, len: 386 },
    BundleProfile { primaries: 8, transfer: 9, group_index: 6, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 10, group_index: 7, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 11, group_index: 8, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 12, group_index: 9, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 13, group_index: 10, offset_in_group: 1760, len: 440 },
    BundleProfile { primaries: 8, transfer: 14, group_index: 11, offset_in_group: 2200, len: 440 },
    BundleProfile { primaries: 8, transfer: 15, group_index: 12, offset_in_group: 2200, len: 440 },
    BundleProfile { primaries: 8, transfer: 16, group_index: 13, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 17, group_index: 14, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 8, transfer: 18, group_index: 15, offset_in_group: 32620, len: 6524 },
    BundleProfile { primaries: 9, transfer: 1, group_index: 0, offset_in_group: 2200, len: 440 },
    BundleProfile { primaries: 9, transfer: 4, group_index: 1, offset_in_group: 2316, len: 386 },
    BundleProfile { primaries: 9, transfer: 5, group_index: 2, offset_in_group: 2316, len: 386 },
    BundleProfile { primaries: 9, transfer: 6, group_index: 3, offset_in_group: 2640, len: 440 },
    BundleProfile { primaries: 9, transfer: 7, group_index: 4, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 8, group_index: 5, offset_in_group: 2316, len: 386 },
    BundleProfile { primaries: 9, transfer: 9, group_index: 6, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 10, group_index: 7, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 11, group_index: 8, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 12, group_index: 9, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 13, group_index: 10, offset_in_group: 2200, len: 440 },
    BundleProfile { primaries: 9, transfer: 14, group_index: 11, offset_in_group: 2640, len: 440 },
    BundleProfile { primaries: 9, transfer: 15, group_index: 12, offset_in_group: 2640, len: 440 },
    BundleProfile { primaries: 9, transfer: 16, group_index: 13, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 17, group_index: 14, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 9, transfer: 18, group_index: 15, offset_in_group: 39144, len: 6524 },
    BundleProfile { primaries: 10, transfer: 1, group_index: 0, offset_in_group: 2640, len: 440 },
    BundleProfile { primaries: 10, transfer: 4, group_index: 1, offset_in_group: 2702, len: 386 },
    BundleProfile { primaries: 10, transfer: 5, group_index: 2, offset_in_group: 2702, len: 386 },
    BundleProfile { primaries: 10, transfer: 6, group_index: 3, offset_in_group: 3080, len: 440 },
    BundleProfile { primaries: 10, transfer: 7, group_index: 4, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 8, group_index: 5, offset_in_group: 2702, len: 386 },
    BundleProfile { primaries: 10, transfer: 9, group_index: 6, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 10, group_index: 7, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 11, group_index: 8, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 12, group_index: 9, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 13, group_index: 10, offset_in_group: 2640, len: 440 },
    BundleProfile { primaries: 10, transfer: 14, group_index: 11, offset_in_group: 3080, len: 440 },
    BundleProfile { primaries: 10, transfer: 15, group_index: 12, offset_in_group: 3080, len: 440 },
    BundleProfile { primaries: 10, transfer: 16, group_index: 13, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 17, group_index: 14, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 10, transfer: 18, group_index: 15, offset_in_group: 45668, len: 6524 },
    BundleProfile { primaries: 11, transfer: 1, group_index: 0, offset_in_group: 3080, len: 440 },
    BundleProfile { primaries: 11, transfer: 4, group_index: 1, offset_in_group: 3088, len: 386 },
    BundleProfile { primaries: 11, transfer: 5, group_index: 2, offset_in_group: 3088, len: 386 },
    BundleProfile { primaries: 11, transfer: 6, group_index: 3, offset_in_group: 3520, len: 440 },
    BundleProfile { primaries: 11, transfer: 7, group_index: 4, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 8, group_index: 5, offset_in_group: 3088, len: 386 },
    BundleProfile { primaries: 11, transfer: 9, group_index: 6, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 10, group_index: 7, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 11, group_index: 8, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 12, group_index: 9, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 13, group_index: 10, offset_in_group: 3080, len: 440 },
    BundleProfile { primaries: 11, transfer: 14, group_index: 11, offset_in_group: 3520, len: 440 },
    BundleProfile { primaries: 11, transfer: 15, group_index: 12, offset_in_group: 3520, len: 440 },
    BundleProfile { primaries: 11, transfer: 16, group_index: 13, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 17, group_index: 14, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 11, transfer: 18, group_index: 15, offset_in_group: 52192, len: 6524 },
    BundleProfile { primaries: 12, transfer: 1, group_index: 0, offset_in_group: 3520, len: 440 },
    BundleProfile { primaries: 12, transfer: 4, group_index: 1, offset_in_group: 3474, len: 386 },
    BundleProfile { primaries: 12, transfer: 5, group_index: 2, offset_in_group: 3474, len: 386 },
    BundleProfile { primaries: 12, transfer: 6, group_index: 3, offset_in_group: 3960, len: 440 },
    BundleProfile { primaries: 12, transfer: 7, group_index: 4, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 8, group_index: 5, offset_in_group: 3474, len: 386 },
    BundleProfile { primaries: 12, transfer: 9, group_index: 6, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 10, group_index: 7, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 11, group_index: 8, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 12, group_index: 9, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 13, group_index: 10, offset_in_group: 3520, len: 440 },
    BundleProfile { primaries: 12, transfer: 14, group_index: 11, offset_in_group: 3960, len: 440 },
    BundleProfile { primaries: 12, transfer: 15, group_index: 12, offset_in_group: 3960, len: 440 },
    BundleProfile { primaries: 12, transfer: 16, group_index: 13, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 17, group_index: 14, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 12, transfer: 18, group_index: 15, offset_in_group: 58716, len: 6524 },
    BundleProfile { primaries: 22, transfer: 1, group_index: 0, offset_in_group: 3960, len: 440 },
    BundleProfile { primaries: 22, transfer: 4, group_index: 1, offset_in_group: 3860, len: 386 },
    BundleProfile { primaries: 22, transfer: 5, group_index: 2, offset_in_group: 3860, len: 386 },
    BundleProfile { primaries: 22, transfer: 6, group_index: 3, offset_in_group: 4400, len: 440 },
    BundleProfile { primaries: 22, transfer: 7, group_index: 4, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 8, group_index: 5, offset_in_group: 3860, len: 386 },
    BundleProfile { primaries: 22, transfer: 9, group_index: 6, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 10, group_index: 7, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 11, group_index: 8, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 12, group_index: 9, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 13, group_index: 10, offset_in_group: 3960, len: 440 },
    BundleProfile { primaries: 22, transfer: 14, group_index: 11, offset_in_group: 4400, len: 440 },
    BundleProfile { primaries: 22, transfer: 15, group_index: 12, offset_in_group: 4400, len: 440 },
    BundleProfile { primaries: 22, transfer: 16, group_index: 13, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 17, group_index: 14, offset_in_group: 65240, len: 6524 },
    BundleProfile { primaries: 22, transfer: 18, group_index: 15, offset_in_group: 65240, len: 6524 },
];
