//! Runtime decode path for the bundled, transfer-grouped CICP→ICC blob.
//!
//! The blob ([`CICP_BUNDLE_LZ4`]) is 16 independent LZ4-HC blocks — one per
//! H.273 transfer-characteristics code — concatenated into one committed asset
//! and embedded via `include_bytes!`. The companion [`BUNDLE_GROUPS`] /
//! [`BUNDLE_PROFILES`] tables (generated by `icc-gen`'s `cicp_bundle_gen`
//! binary) say where each group lives in the blob and where each profile lives
//! inside its group's *decoded* bytes.
//!
//! On a lookup we binary-search [`BUNDLE_PROFILES`] for the requested
//! `(primaries, transfer)`; on a hit we decode **only that group** (lazily,
//! once, into a per-group [`OnceBox`] cache) and slice the profile out. Only the
//! groups actually touched stay resident — there's no permanent ~600 KiB
//! allocation of the whole decoded set. The decoded group lives in a `'static`
//! `OnceBox`, so the sliced profile is returned as a zero-copy
//! `Cow::Borrowed(&'static [u8])`.
//!
//! Decode uses `lz4_flex`'s `safe-decode` (pure-Rust, `no_std`), so the whole
//! path stays within `#![forbid(unsafe_code)]`.

use alloc::borrow::Cow;
use alloc::boxed::Box;
use alloc::vec;
use alloc::vec::Vec;

use once_cell::race::OnceBox;

use super::cicp_bundle_index::{BUNDLE_GROUPS, BUNDLE_PROFILES, CICP_BUNDLE_LZ4, NUM_GROUPS};

/// Per-group decode cache. Each slot lazily holds one group's decoded bytes;
/// only groups that are actually requested are ever populated. A `static`
/// `OnceBox` yields a `&'static` reference from `get_or_init`, which is what
/// lets the public lookup hand back a borrowed (zero-copy) profile.
///
/// `OnceBox<T>` requires `T: Sized`, so the decoded bytes live in a `Vec<u8>`
/// (boxed by the cell) rather than a bare `[u8]`.
static GROUP_CACHE: [OnceBox<Vec<u8>>; NUM_GROUPS] = [const { OnceBox::new() }; NUM_GROUPS];

/// Decode group `group_index` (idempotent; cached for the program's lifetime).
///
/// Returns the group's full decoded bytes. `decompress_into` writes into an
/// exactly-sized buffer (the decompressed length is known from the index), so
/// there's no size-prefix parsing and no reallocation.
fn decode_group(group_index: usize) -> &'static [u8] {
    GROUP_CACHE[group_index].get_or_init(|| {
        let g = &BUNDLE_GROUPS[group_index];
        let block = &CICP_BUNDLE_LZ4[g.blob_offset..g.blob_offset + g.compressed_len];
        let mut out = vec![0u8; g.decompressed_len];
        let written = lz4_flex::block::decompress_into(block, &mut out)
            .expect("bundled CICP ICC group failed to LZ4-decode (corrupt committed asset)");
        debug_assert_eq!(
            written, g.decompressed_len,
            "decoded length disagrees with the index — regenerate the bundle"
        );
        Box::new(out)
    })
}

/// Look up a bundled ICC profile for a raw CICP `(primaries, transfer)` pair.
///
/// Returns the profile bytes if the combination is in the bundle, decoding (and
/// caching) the owning transfer group on first touch. The slice borrows the
/// `'static` group cache, so it's a zero-copy `Cow::Borrowed`.
///
/// Returns `None` for combinations not in the bundle (the sRGB / BT.709 default
/// pair handled upstream as `NotNeeded`, and any combo moxcms couldn't represent
/// at generation time).
pub(crate) fn bundled_profile_for_cicp(primaries: u8, transfer: u8) -> Option<Cow<'static, [u8]>> {
    let idx = BUNDLE_PROFILES
        .binary_search_by(|p| (p.primaries, p.transfer).cmp(&(primaries, transfer)))
        .ok()?;
    let p = &BUNDLE_PROFILES[idx];
    // Consistency: the profile's owning group must be the one that covers its
    // transfer. Cheap guard against an index/blob desync after a regen.
    debug_assert_eq!(
        BUNDLE_GROUPS[p.group_index].transfer, p.transfer,
        "profile→group transfer mismatch in the generated index"
    );
    let group = decode_group(p.group_index);
    let bytes = &group[p.offset_in_group..p.offset_in_group + p.len];
    Some(Cow::Borrowed(bytes))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn blob_offsets_and_lengths_are_consistent() {
        // The concatenated groups must exactly tile the blob with no gaps or
        // overruns, in group order.
        let mut expected_offset = 0usize;
        for g in &BUNDLE_GROUPS {
            assert_eq!(
                g.blob_offset, expected_offset,
                "group blob offsets must be contiguous"
            );
            expected_offset += g.compressed_len;
        }
        assert_eq!(
            expected_offset,
            CICP_BUNDLE_LZ4.len(),
            "groups must exactly cover the blob"
        );
    }

    #[test]
    fn every_group_decodes_to_its_declared_length() {
        for i in 0..NUM_GROUPS {
            let decoded = decode_group(i);
            assert_eq!(
                decoded.len(),
                BUNDLE_GROUPS[i].decompressed_len,
                "group {i} decoded length mismatch"
            );
        }
    }

    #[test]
    fn every_profile_slice_is_in_bounds_and_is_a_valid_icc() {
        for p in &BUNDLE_PROFILES {
            let got = bundled_profile_for_cicp(p.primaries, p.transfer)
                .expect("indexed profile must resolve");
            assert_eq!(got.len(), p.len, "profile length mismatch");
            // Minimal ICC structural sanity: 'acsp' signature at byte 36.
            assert!(got.len() >= 40, "profile too short to be an ICC");
            assert_eq!(
                &got[36..40],
                b"acsp",
                "({}, {}) is not a valid ICC profile (missing 'acsp')",
                p.primaries,
                p.transfer
            );
        }
    }

    #[test]
    fn miss_returns_none() {
        // primaries=2 (Unspecified) is never in the bundle.
        assert!(bundled_profile_for_cicp(2, 13).is_none());
        // The sRGB-default pair is handled upstream as NotNeeded and excluded.
        assert!(bundled_profile_for_cicp(1, 13).is_none());
        assert!(bundled_profile_for_cicp(1, 1).is_none());
    }
}
