&[
    (0x0bcc_b096_6018_2f67, TF::Gamma22,  0),  // gray gamma 2 2 653b586c
    (0x1381_5d85_fc30_6e87, TF::Srgb,  1),  // generic gray gamma 2 2 profile ee2f821d
    (0x15be_564c_995c_a5e6, TF::Srgb,  1),  // with srgb trc 6ee1b837
    (0x1da1_a0cc_3fdb_d3d8, TF::Gamma18, 11),  // generic gray profile 94722fe2
    (0x2b1a_75e7_7031_1422, TF::Srgb,  1),  // compact-icc-sGrey-v4
    (0x4a53_6d63_5caf_c238, TF::Srgb, 13),  // compact-icc-sGrey-v2-micro
    (0x7386_f664_c077_629d, TF::Srgb,  1),  // generic gray gamma 2 2 profile 73d50455
    (0x7407_e42a_41a5_1622, TF::Srgb, 56),  // compact-icc-sGrey-v2-nano
    (0x79e6_dee8_8e35_a74e, TF::Gamma22,  0),  // gray gamma 2 2 27271ce6
    (0x8f8f_6aeb_0b1b_cffc, TF::Gamma22,  0),  // gray gamma 2 2 de47062f
    (0x922e_3e93_9b73_5718, TF::Gamma18, 11),  // epson gray - gamma 1 8 03ecbaeb
    (0xa02b_b3b8_ed69_63d3, TF::Gamma18, 11),  // generic gray profile 10233312
    (0xaf06_5a1e_06f8_3c15, TF::Gamma18, 11),  // gray gamma 1 8 a594b85c
    (0xb0bb_06d4_d589_eca9, TF::Gamma22,  0),  // gray gamma 2 2 f00165cf
    (0xb893_86de_37c7_440c, TF::Srgb,  2),  // compact-icc-sGrey-v2-magic
    (0xc3c9_13c7_dbf6_1b16, TF::Srgb,  1),  // with srgb trc 14abccd5
    (0xd866_a1ec_636e_f452, TF::Gamma22,  0),  // calibrated gray colorspace 397a83da
    (0xe857_d652_9f66_d7f7, TF::Gamma18, 11),  // generic gray profile 0faa32c0
    (0xecc8_370f_ccf8_230f, TF::Srgb,  1),  // Generic Gray Gamma 2.2 Profile
]
